// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyCFHF3UNDCUJ53C5ZE-c5W2PLW1mtYCSf4',
  //   appId: '1:553907136224:web:a1ef500962456f4f539285',
  //   messagingSenderId: '553907136224',
  //   projectId: 'meat-delivery-c9079',
  //   authDomain: 'meat-delivery-c9079.firebaseapp.com',
  //   storageBucket: 'meat-delivery-c9079.appspot.com',
  //   measurementId: 'G-H9PDKT6H4Q',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2FQ5r6OrT2V_Sp4e0Q_eotF6wHoA0S4',
    appId: '1:553907136224:android:88fed95e17f97445539285',
    messagingSenderId: '553907136224',
    projectId: 'meat-delivery-c9079',
    storageBucket: 'meat-delivery-c9079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FavtayzlCnuaPZ62uMUUbixp72ABavU',
    appId: '1:553907136224:ios:1066f3a3a73a5121539285',
    messagingSenderId: '553907136224',
    projectId: 'meat-delivery-c9079',
    storageBucket: 'meat-delivery-c9079.appspot.com',
    iosBundleId: 'com.prt.meatDelivery',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyA0FavtayzlCnuaPZ62uMUUbixp72ABavU',
  //   appId: '1:553907136224:ios:1066f3a3a73a5121539285',
  //   messagingSenderId: '553907136224',
  //   projectId: 'meat-delivery-c9079',
  //   storageBucket: 'meat-delivery-c9079.appspot.com',
  //   iosBundleId: 'com.prt.meatDelivery',
  // );
  //
  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyCFHF3UNDCUJ53C5ZE-c5W2PLW1mtYCSf4',
  //   appId: '1:553907136224:web:694f2219888987e2539285',
  //   messagingSenderId: '553907136224',
  //   projectId: 'meat-delivery-c9079',
  //   authDomain: 'meat-delivery-c9079.firebaseapp.com',
  //   storageBucket: 'meat-delivery-c9079.appspot.com',
  //   measurementId: 'G-NXM81B338S',
  // );
}
